import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateAndSaveReport({
    required String patientName,
    required String patientId,
    required String score,
    required String status,
    Map<String, dynamic>? resultData,
  }) async {
    final pdf = pw.Document();

    final now = DateTime.now();
    final formatter = DateFormat('yyyy-MM-dd HH:mm');
    final dateString = formatter.format(now);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('AnxiSense Clinical Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(dateString, style: pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 20),

              // Patient Info
              pw.Text('Patient Information', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Text('Name: ${patientName.toUpperCase()}'),
              pw.Text('Patient ID: $patientId'),
              pw.SizedBox(height: 20),

              // Assessment Results
              pw.Container(
                padding: const pw.EdgeInsets.all(15),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('AI-Generated Anxiety Score', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 10),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Score: $score', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                        pw.Text('Status: ${status.toUpperCase()}', style: pw.TextStyle(fontSize: 16)),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Emotion Analysis
              pw.Text('Emotion Analysis', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              if (resultData != null && resultData['emotions'] != null)
                ... (resultData['emotions'] as Map).entries.map((e) {
                  final val = (e.value as num).toDouble();
                  return pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 5),
                    child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(e.key.toString().toUpperCase()),
                        pw.Text('${val.toStringAsFixed(4)}%'),
                      ],
                    ),
                  );
                }).toList()
              else
                pw.Text('Detailed emotion data unavailable.'),
              
              pw.SizedBox(height: 20),
              if (resultData != null && resultData['dominant_emotion'] != null)
                pw.Text('Dominant Emotion: ${resultData['dominant_emotion'].toString().toUpperCase()}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),

              pw.SizedBox(height: 30),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Center(child: pw.Text('Report generated by AnxiSense AI Assessment System', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey))),
            ],
          );
        },
      ),
    );

    // Save or Print
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'AnxiSense_Report_${patientId}_${now.millisecondsSinceEpoch}.pdf',
    );
  }
}
